import { ArrowDownRight, ArrowRight, ArrowUpRight, BadgeCheck, PackageCheck, RefreshCw, ShieldCheck } from 'lucide-react'
import { Link } from 'react-router-dom'
import PromotionBanner from '../components/home/PromotionBanner'
import ProductGrid from '../components/product/ProductGrid'
import { useProducts } from '../context/ProductContext'
import { useUI } from '../context/UIContext'
import { banners } from '../data/products'

export default function Home() {
  const { notify } = useUI()
  const { products, categories, brands, sizes } = useProducts()
  const brandNames = brands.map((brand) => typeof brand === 'string' ? brand : brand.name)
  const hero = banners[0]
  const featured = products.filter((product) => product.featured).slice(0, 4)
  return <main>
    <section className="hero-section"><div className="hero-copy"><span className="eyebrow"><span className="eyebrow-line" /> YOUR NEXT FAVORITE PAIR</span><h1>Good shoes.<br /><em>Better days.</em></h1><p>Thoughtfully sourced footwear, ready for another great story. Find your perfect pair at a price that feels right.</p><div className="hero-actions"><Link className="button button-dark" to="/shop">Find your pair <ArrowRight size={16} /></Link><Link to="/shop?category=new-arrivals" className="text-link">Explore new arrivals <ArrowUpRight size={16} /></Link></div><div className="hero-note"><div className="avatar-stack"><span>✓</span><span>✓</span><span>✓</span></div><span><b>Good shoes, checked.</b><br />Every pair gets a second look.</span></div></div><div className="hero-visual"><img src={hero.image} alt="Classic sneakers styled for everyday wear" /><div className="hero-image-note"><span>THE EVERYDAY EDIT</span><b>Made for the miles ahead.</b></div><div className="hero-vertical">PRE-LOVED. WELL-LOVED.</div></div><a className="hero-scroll" href="#discover"><ArrowDownRight size={16} /> SCROLL TO DISCOVER</a><div className="hero-count">01 <span>/ 03</span></div></section>
    <section className="value-strip"><div><ShieldCheck /><span><b>Quality checked</b><small>Pairs we’d wear ourselves</small></span></div><div><RefreshCw /><span><b>Easy returns</b><small>Shop with confidence</small></span></div><div><PackageCheck /><span><b>Nationwide delivery</b><small>Across Pakistan</small></span></div><div><BadgeCheck /><span><b>Better by design</b><small>Good shoes, less waste</small></span></div></section>
    <section className="section section-pad" id="discover"><div className="section-heading"><div><span className="eyebrow">A LITTLE SOMETHING FOR EVERY STEP</span><h2>Find your kind of <em>move.</em></h2></div><Link className="text-link" to="/shop">Shop all styles <ArrowRight size={16} /></Link></div><div className="category-grid">{categories.map((category, index) => <Link to={`/shop?category=${category.slug}`} className={`category-tile category-tile-${index}`} key={category.slug}><img src={category.image} alt="" loading="lazy" /><span className="category-tint" /><div><span className="eyebrow">EXPLORE THE EDIT</span><h3>{category.name}</h3><span className="category-cta">Shop collection <ArrowUpRight size={16} /></span></div></Link>)}</div></section>
    <section className="section section-pad featured-section"><div className="section-heading"><div><span className="eyebrow">GOOD PAIRS, GREAT STORIES</span><h2>In the <em>spotlight.</em></h2></div><Link className="text-link" to="/shop?sort=featured">View all footwear <ArrowRight size={16} /></Link></div><ProductGrid products={featured} /></section>
    <PromotionBanner image="https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=1200&q=85" eyebrow="A SMARTER KIND OF SHOPPING" title={<>Good for your feet.<br /><em>Better for the planet.</em></>} description="Great footwear deserves more than one chapter. Every pre-loved pair is carefully checked, ready to get back out there, and priced to make sense." action="Shop pre-loved" href="/shop?condition=Like+New" />
    <section className="section section-pad browse-sections"><div className="section-heading"><div><span className="eyebrow">MAKE IT YOURS</span><h2>Shop by <em>size.</em></h2><p>Find the right fit, without the endless scroll.</p></div><Link className="text-link" to="/size-guide">Need a size guide? <ArrowRight size={16} /></Link></div><div className="size-row">{sizes.map((size) => <Link key={size} to={`/shop?size=${size}`}><small>EU</small>{size}</Link>)}</div></section>
    <section className="brand-condition-wrap"><div className="section section-pad brand-section"><span className="eyebrow">THE NAMES YOU KNOW</span><h2>Shop by <em>brand.</em></h2><div className="brand-list">{brandNames.map((brand, index) => <Link to={`/shop?brand=${encodeURIComponent(brand)}`} key={brand}><span>{brand}</span><small>0{index + 1}</small></Link>)}</div></div><div className="condition-card"><span className="eyebrow">GOOD SHOES. HONEST CONDITION.</span><h2>Find your <em>forever pair.</em></h2><p>Every pair gets a clear, honest condition rating. No guesswork, just good footwear.</p>{['New', 'Like New', 'Used', 'Refurbished'].map((condition) => <Link to={`/shop?condition=${encodeURIComponent(condition)}`} key={condition}>{condition}<ArrowUpRight size={16} /></Link>)}</div></section>
    <section className="newsletter"><div><span className="eyebrow">A GOOD THING IN YOUR INBOX</span><h2>First dibs. <em>Good deals.</em></h2><p>New finds and good news, now and then. Never the noise.</p></div><form onSubmit={(event) => { event.preventDefault(); event.currentTarget.reset(); notify('You’re on the list. Look out for good things!') }}><label className="sr-only" htmlFor="newsletter-email">Email address</label><input id="newsletter-email" type="email" placeholder="Your email address" required /><button aria-label="Subscribe" type="submit"><ArrowRight /></button><small>By subscribing, you agree to our very occasional emails.</small></form></section>
  </main>
}
