import { ArrowRight, Check, Mail, MapPin, Phone, Ruler, ShieldCheck, Truck } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useUI } from '../context/UIContext'

const policyCopy = {
  '/return-policy': { eyebrow: 'NO PRESSURE, JUST GOOD FITS', title: 'Returns, made easy.', intro: 'Sometimes a pair just isn’t your pair. That’s alright. We want you to feel good about every step.', icon: ShieldCheck, sections: [['14 days to decide', 'Let us know within 14 days of receiving your order. Items should be unworn, in their original packaging, and in the condition they arrived.'], ['How to start a return', 'Get in touch with our team at hello@mgears.pk with your order number and a short note. We’ll help arrange the next step.'], ['Refunds & exchanges', 'Once your return is checked, we’ll help with an exchange or refund via your original payment method. Cash-on-delivery refunds are arranged directly with you.'], ['A quick note', 'For hygiene reasons, worn footwear cannot be returned. Sale items may have different return conditions, which we’ll make clear before purchase.']] },
  '/shipping-policy': { eyebrow: 'GOOD THINGS ARE ON THE WAY', title: 'Shipping & delivery.', intro: 'We deliver across Pakistan, bringing well-loved footwear right to your door.', icon: Truck, sections: [['Delivery times', 'Most orders are delivered within 3–5 business days. Remote areas may take a little longer, and we’ll keep you updated along the way.'], ['Delivery fees', 'Enjoy complimentary delivery on orders over Rs. 25,000. A Rs. 350 delivery fee applies to smaller orders.'], ['Order updates', 'Use the order number in your confirmation to check progress on our Track Order page. Need a hand? Our team is happy to help.'], ['Cash on delivery', 'Cash on delivery is available for eligible locations. Payment and order details are simulated in this frontend demo.']] },
}
function PolicyPage({ type }) {
  const content = policyCopy[type]
  const Icon = content.icon
  return <main className="subpage policy-page"><div className="breadcrumbs"><Link to="/">Home</Link><span>/</span><span>{content.title}</span></div><section className="policy-hero"><span className="policy-icon"><Icon size={23} /></span><span className="eyebrow">{content.eyebrow}</span><h1>{content.title}</h1><p>{content.intro}</p></section><div className="policy-layout"><div className="policy-nav"><span className="eyebrow">NEED TO KNOW</span><Link to="/shipping-policy">Shipping details <ArrowRight size={14} /></Link><Link to="/return-policy">Returns & exchanges <ArrowRight size={14} /></Link><Link to="/size-guide">Find your fit <ArrowRight size={14} /></Link><Link to="/contact">Still have questions? <ArrowRight size={14} /></Link></div><div className="policy-content">{content.sections.map(([heading, body], index) => <article key={heading}><span>0{index + 1}</span><div><h2>{heading}</h2><p>{body}</p></div></article>)}</div></div></main>
}
export function ReturnPolicyPage() { return <PolicyPage type="/return-policy" /> }
export function ShippingPolicyPage() { return <PolicyPage type="/shipping-policy" /> }

export function SizeGuidePage() {
  const conversions = [[36, 3.5, 5.5, 22.5], [37, 4, 6, 23.3], [38, 5, 7, 24], [39, 6, 8, 24.7], [40, 6.5, 8.5, 25.3], [41, 7, 9, 26], [42, 8, 10, 26.7], [43, 9, 11, 27.3], [44, 9.5, 11.5, 28]]
  return <main className="subpage size-guide-page"><div className="breadcrumbs"><Link to="/">Home</Link><span>/</span><span>Size guide</span></div><section className="size-guide-hero"><span className="policy-icon"><Ruler size={22} /></span><span className="eyebrow">THE RIGHT FIT MAKES ALL THE DIFFERENCE</span><h1>Your guide to <em>getting it right.</em></h1><p>Sizes can differ a little by brand. Use this chart as a helpful starting point.</p></section><div className="size-guide-layout"><div className="size-table-wrap"><table className="size-table"><thead><tr><th>EU</th><th>UK</th><th>US (Men)</th><th>Foot length (cm)</th></tr></thead><tbody>{conversions.map((row) => <tr key={row[0]}>{row.map((value, index) => <td key={index}>{value}</td>)}</tr>)}</tbody></table><p className="table-note">Conversions are a guide only. For the most accurate fit, check the brand’s sizing information.</p></div><aside className="measure-card"><span className="eyebrow">MEASURE AT HOME</span><h2>Find your foot length.</h2><ol><li><span>01</span> Place a sheet of paper against a wall.</li><li><span>02</span> Stand with your heel gently against the wall.</li><li><span>03</span> Mark the tip of your longest toe.</li><li><span>04</span> Measure from the wall to your mark in centimetres.</li></ol><Link to="/shop">Shop your size <ArrowRight size={15} /></Link></aside></div></main>
}

export function ContactPage() {
  const { notify } = useUI()
  const submit = (event) => { event.preventDefault(); event.currentTarget.reset(); notify('Thanks for reaching out. We’ll be in touch soon.') }
  return <main className="subpage contact-page"><div className="breadcrumbs"><Link to="/">Home</Link><span>/</span><span>Contact</span></div><div className="contact-layout"><section className="contact-copy"><span className="eyebrow">A REAL PERSON, RIGHT HERE</span><h1>Need a hand? <em>We’re here.</em></h1><p>Questions about fit, an order, or just want to talk shoes? We’d love to hear from you.</p><div className="contact-methods"><a href="mailto:hello@mgears.pk"><span><Mail size={18} /></span><div><small>EMAIL US</small><b>hello@mgears.pk</b></div></a><a href="tel:+923001234567"><span><Phone size={18} /></span><div><small>CALL OR WHATSAPP</small><b>+92 300 123 4567</b></div></a><div><span><MapPin size={18} /></span><div><small>BASED IN</small><b>Lahore, Pakistan</b></div></div></div><div className="contact-hours"><Check size={16} /> We usually get back within one business day.</div></section><form className="contact-form" onSubmit={submit}><span className="eyebrow">SEND US A NOTE</span><div className="form-grid"><label>Name<input name="name" autoComplete="name" required /></label><label>Email<input name="email" type="email" autoComplete="email" required /></label><label>Phone<input name="phone" type="tel" autoComplete="tel" /></label><label>Subject<select name="subject" defaultValue="" required><option value="" disabled>Choose a topic</option><option>Order help</option><option>Fit & sizing</option><option>Returns</option><option>Something else</option></select></label><label className="wide">Message<textarea name="message" rows="5" required /></label></div><button className="button button-dark">Send your message <ArrowRight size={16} /></button><p className="demo-note">This form is a frontend demo and does not send your message.</p></form></div></main>
}

export function AboutPage() {
  return <main className="about-page"><section className="about-hero"><div><span className="eyebrow">GOOD SHOES DESERVE ANOTHER STORY</span><h1>We believe in <em>the long walk.</em></h1><p>MGEARS is a considered footwear edit for the steps you take every day. We find pairs with more to give, check them carefully, and help them find their next great home.</p><Link className="button button-dark" to="/shop">Find your next pair <ArrowRight size={16} /></Link></div><img src="https://images.unsplash.com/photo-1600185365483-26d7a4cc7519?auto=format&fit=crop&w=1100&q=85" alt="A fresh pair of everyday sneakers" /></section><section className="about-values"><div><span className="eyebrow">01 / A BETTER SECOND CHAPTER</span><h2>More life in every pair.</h2><p>Good footwear should get out there. Our pre-loved edit helps great shoes keep moving instead of sitting on a shelf.</p></div><div><span className="eyebrow">02 / QUALITY, WITHOUT THE GUESSWORK</span><h2>Checked by people who care.</h2><p>We inspect every pair and describe its condition honestly, so you can choose with confidence and know what to expect.</p></div><div><span className="eyebrow">03 / GOOD FIT FOR REAL LIFE</span><h2>Thoughtful finds, fair prices.</h2><p>From everyday favorites to trail-ready pairs, MGEARS makes it easier to discover the right footwear for your next step.</p></div></section><section className="about-end"><span className="eyebrow">YOUR NEXT FAVORITE PAIR IS OUT THERE</span><h2>Let’s find <em>it together.</em></h2><Link className="button button-light" to="/shop">Explore the collection <ArrowRight size={16} /></Link></section></main>
}

export function NotFoundPage() {
  return <main className="not-found"><span className="not-found-number">4004</span><span className="eyebrow">THIS PAGE TOOK A WRONG TURN</span><h1>Page not found.</h1><p>The page you’re looking for might have moved on. The good shoes are still right here.</p><Link className="button button-dark" to="/">Back to home <ArrowRight size={16} /></Link></main>
}
