/* eslint-disable react-refresh/only-export-components */
export * from "./DashboardPage";
export * from "./CatalogListPages";
export * from "./ProductFormPage";
export * from "./ProductDetailPage";
export * from "./CatalogFormPages";
export * from "./OrderPages";
export * from "./CustomerPages";
export * from "./InventoryPage";
export * from "./DiscountsPage";
export * from "./SettingsPage";
